version: "2.0"
services:
  clion:
    build: .
    network_mode: host
    volumes:
      - "./workspace:/workspace"
      - "./idea-config:/root/.CLion2018.2"
      - "./java-config:/root/.java"
      - "~/.Xauthority:/root/.Xauthority:rw"
      - "/tmp/.X11-unix"
    environment:
      DISPLAY: "unix:0"
    cap_add:
      - SYS_PTRACE
    privileged: true
    command: /opt/clion-2018.2.6/bin/clion.sh
